### ISSUE TITLE
Some pool state no update!

### ISSUE THREAD

**Issue by Tony-1240645041** [XDagger/XDagger.github.io#149]
The "xdag.club" pool state no update on the page "xdag.io/pools", and the "xdag.club" information is correct in "pool. yml" file.

**Comment by timlah** [comment]
Hey, thanks for notifying us about the issue. 

Our setup expects your http server to include a Last-Modified header in it's responses. It seems that both http://xdag.club/state.txt and http://xdag.club/stats.txt don't have that header set right now.

We use this header to determine whether the file has been updated recently (in the last 5 minutes) or not. If it's older than 5 minutes or there is no Last-Modified header, the pool state is shown as unknown and stats as null.

**Comment by Tony-1240645041** [comment]
I switched to nginx as a web server, and now the status can be updated, but my mining address is still wrong.pool.yml file is mining.xdag.club:13654,but xdag.io/pools is node.xdag.club:13655.

**Comment by timlah** [comment]
Fixed. Let me know if everything is working now on your end and I'll close this issue.

**Comment by Tony-1240645041** [comment]
ok,thank you.
