### ISSUE TITLE
mac connection to website fails

### ISSUE THREAD

**Issue by xrdavies** [XDagger/XDagger.github.io#4]
[Original one #49 ](https://github.com/XDagger/xdag/issues/49)

Mac connection to website https fail, httpse OK

**Comment by Lavande** [comment]
Https also failed here. 
Version 65.0.3325.181 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit)
Http OK

**Comment by mathsw** [comment]
HTTPS has been fixed as of commit `66c6f53`
